version: '3'
services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:latest
    volumes:
      - pb_data:/pb_data
    ports:
      - "8090:8090"
  bot:
    build: .
    env_file: .env
    depends_on:
      - pocketbase
volumes:
  pb_data:
